library(dplyr)
library(magrittr)
library(shiny)
library(shinythemes)
library(tidyverse)
library(shinyWidgets)
library(shinyjs)
library(shinycssloaders)
library(shinybusy)
library(kableExtra)
library(shinyBS)
library(rsconnect)
library(auth0)
library(DT)
library(readxl)
library(kableExtra)
library(knitr)
library(ggbeeswarm)
library(patchwork)
library(performance)
library(easystats)

source("ui.R")
source("server.R")

# runApp(host="0.0.0.0", port=8080)
# runApp(host="0.0.0.0", port=8080, launch.browser = TRUE)


